export const articleSeed = [
  {
    title: 'Learning',
    content:
      '\n**FrontendMasters:**\n\nUrl: https://frontendmasters.com/courses/ \n\nLogin: learning@dektry.com\n\nPassword: EtG8btsi@*ncxsLNW\n\n**Udemy:**\n\nUrl: https://www.udemy.com/home/my-courses/learning/\n\nLogin: learning@dektry.com\n\nPassword: -FPuFZ4*g4hzabG@L\n',
    create_at: new Date(),
    update_at: new Date(),
    read_positions: [
      'CEO',
      'Business Development manager',
      'Full stack trainee',
      'Back-end trainee',
      'Front-end developer',
      'Marketing Manager',
      'Front-end trainee',
      'Swift developer',
      'Full stack developer',
      'Back-end developer',
    ],
    edit_positions: [
      'CEO',
      'Business Development manager',
      'Full stack trainee',
      'Back-end trainee',
      'Front-end developer',
      'Marketing Manager',
      'Front-end trainee',
      'Swift developer',
      'Full stack developer',
      'Back-end developer',
    ],
  },
  {
    title: 'Onboarding',
    content:
      'Each newcomer after coming into the company should be assigned to a mentor. This person describes a full situation of the company - makes an intro and controls that a newcomer has all accesses and rights.\n\n### Workplace\n\n* Right now Dektry - is a remote working company. That means, that each employee works from home.\n* PC - should be managed by Yury.\n\n### Services\n\nEach newcomer should get an email address as following: name.surname@dektry.com. \n\nThen a new person should be added into company resources:\n\n* **Jira** - task control system. Here employee manages his tasks.\n* **Hubstaff** - time tracker. Here employee manages hist work logs.\n* **Telegram** - main communication engine.\n\n\n### Vacations\n\nAll holidays are served by local calendar.\n\nTime off requests serves according to local laws ( days per year).\n',
    create_at: new Date(),
    update_at: new Date(),
    read_positions: [
      'CEO',
      'Business Development manager',
      'Full stack trainee',
      'Back-end trainee',
      'Front-end developer',
      'Marketing Manager',
      'Front-end trainee',
      'Swift developer',
      'Full stack developer',
      'Back-end developer',
    ],
    edit_positions: [
      'CEO',
      'Business Development manager',
      'Full stack trainee',
      'Back-end trainee',
      'Front-end developer',
      'Marketing Manager',
      'Front-end trainee',
      'Swift developer',
      'Full stack developer',
      'Back-end developer',
    ],
  },
  {
    title: 'Mailbox',
    content:
      "In the near future or already you will receive an email and a password for your corporate mail. Please connect it to a mail client convenient for you.\n\n---\n\n**Incoming Server**: scp117.hosting.reg.ru\n\n**IMAP** Port: 993 \n\n**POP3** Port: 995\n\n---\n**Outgoing Server:** scp117.hosting.reg.ru\n\n**SMTP** Port: 465\n\nIMAP, POP3, and SMTP **require authentication**.\n\n---\n**The following communication rules apply to corporate mail:**\nif someone wrote something to you, it is assumed that you read it **after 15 minutes**. If the letter implies a reply, then you are expected **to reply no later than 30 minutes**. Based on this, I recommend keeping your mail clean and setting up filters for services and notifications.\n\nAnd please don't use corporate email to forward memes:)\n\n---\n\nOnce connected, configure your display name according to this form:\n\n**Dectry | Your name**\n\nAnd set a **signature** for your messages, following the example contained in the messages of your colleagues.\n",
    create_at: new Date(),
    update_at: new Date(),
    read_positions: [
      'CEO',
      'Business Development manager',
      'Full stack trainee',
      'Back-end trainee',
      'Front-end developer',
      'Marketing Manager',
      'Front-end trainee',
      'Swift developer',
      'Full stack developer',
      'Back-end developer',
    ],
    edit_positions: [
      'CEO',
      'Business Development manager',
      'Full stack trainee',
      'Back-end trainee',
      'Front-end developer',
      'Marketing Manager',
      'Front-end trainee',
      'Swift developer',
      'Full stack developer',
      'Back-end developer',
    ],
  },
  {
    title: 'LinkedIn',
    content:
      'Each member of the Dektry team is suggested to have a Linkedin profile. Social media presence plays an important role in creating Dektry’s reputation among the IT community. \n###  To create a profile:\n\n1. Go to [**LinkedIn**](https://www.linkedin.com/), click **“Join”** in the upper right corner.\n2. **Fill in your profile** with personal information, write a short summary in an **“About”** section.\n3. When filling in an “Experience” section, make sure **your profile is associated with [Dektry’s linkedin page](https://www.linkedin.com/company/dektry/)**. Click on Dektry’s icon when it pops up. Choose Location according to where you are based.\n4. Add your **soft** and **hard skills** to the profile, follow some communities.\n5. Connect with your Dektry colleagues\n6. Add your colleagues as teammates. For that go to **“Network”** and press **“Teammates”**.\n7. Endorse your colleagues’ professional and personal skills by clicking on the “+” button in the skills section.\n8. Follow [**Dektry page**](https://www.linkedin.com/company/dektry)\n',
    create_at: new Date(),
    update_at: new Date(),
    read_positions: [
      'CEO',
      'Business Development manager',
      'Full stack trainee',
      'Back-end trainee',
      'Front-end developer',
      'Marketing Manager',
      'Front-end trainee',
      'Swift developer',
      'Full stack developer',
      'Back-end developer',
    ],
    edit_positions: [
      'CEO',
      'Business Development manager',
      'Full stack trainee',
      'Back-end trainee',
      'Front-end developer',
      'Marketing Manager',
      'Front-end trainee',
      'Swift developer',
      'Full stack developer',
      'Back-end developer',
    ],
  },
];

export const accessArticleSeed = {
  name: 'articles',
  position: 'CEO',
};
