export const positionSeed = [
  {
    name: 'Front-end developer',
    duties: 'Some duties',
    requirements: 'Some skills',
    salaryMinLimit: 100,
    salaryMaxLimit: 1000,
  },
  {
    name: 'Back-end developer',
    duties: 'Some duties',
    requirements: 'Some skills',
    salaryMinLimit: 100,
    salaryMaxLimit: 1000,
  },
  {
    name: 'Full stack developer',
    duties: 'Some duties',
    requirements: 'Some skills',
    salaryMinLimit: 100,
    salaryMaxLimit: 1000,
  },
  {
    name: 'Front-end trainee',
    duties: 'Some duties',
    requirements: 'Some skills',
    salaryMinLimit: 100,
    salaryMaxLimit: 1000,
  },
  {
    name: 'Back-end trainee',
    duties: 'Some duties',
    requirements: 'Some skills',
    salaryMinLimit: 100,
    salaryMaxLimit: 1000,
  },
  {
    name: 'Full stack trainee',
    duties: 'Some duties',
    requirements: 'Some skills',
    salaryMinLimit: 100,
    salaryMaxLimit: 1000,
  },
  {
    name: 'Swift developer',
    duties: 'Some duties',
    requirements: 'Some skills',
    salaryMinLimit: 100,
    salaryMaxLimit: 1000,
  },
  {
    name: 'Business Development manager',
    duties: 'Some duties',
    requirements: 'Some skills',
    salaryMinLimit: 100,
    salaryMaxLimit: 1000,
  },
  {
    name: 'Marketing Manager',
    duties: 'Some duties',
    requirements: 'Some skills',
    salaryMinLimit: 100,
    salaryMaxLimit: 1000,
  },
  {
    name: 'CEO',
    duties: 'Some duties',
    requirements: 'Some skills',
    salaryMinLimit: 100,
    salaryMaxLimit: 1000,
  },
  {
    name: 'Deleted position',
    duties: 'Some duties',
    requirements: 'Some skills',
    salaryMinLimit: 0,
    salaryMaxLimit: 0,
  },
];
