export const positionSeed = [
  {
    name: 'Front-end developer',
    duties: 'Some duties',
    requirements: 'Some skills',
    salaryMinLimit: 100,
    salaryMaxLimit: 1000,
    group: 'Developers',
  },
  {
    name: 'Back-end developer',
    duties: 'Some duties',
    requirements: 'Some skills',
    salaryMinLimit: 100,
    salaryMaxLimit: 1000,
    group: 'Developers',
  },
  {
    name: 'Full stack developer',
    duties: 'Some duties',
    requirements: 'Some skills',
    salaryMinLimit: 100,
    salaryMaxLimit: 1000,
    group: 'Developers',
  },
  {
    name: 'Swift developer',
    duties: 'Some duties',
    requirements: 'Some skills',
    salaryMinLimit: 100,
    salaryMaxLimit: 1000,
    group: 'Developers',
  },
  {
    name: 'Business Development manager',
    duties: 'Some duties',
    requirements: 'Some skills',
    salaryMinLimit: 100,
    salaryMaxLimit: 1000,
    group: 'Business developers',
  },
  {
    name: 'Marketing Manager',
    duties: 'Some duties',
    requirements: 'Some skills',
    salaryMinLimit: 100,
    salaryMaxLimit: 1000,
    group: 'Business developers',
  },
  {
    name: 'CEO',
    duties: 'Some duties',
    requirements: 'Some skills',
    salaryMinLimit: 100,
    salaryMaxLimit: 1000,
    group: 'Administration',
  },
  {
    name: 'Deleted position',
    duties: 'Some duties',
    requirements: 'Some skills',
    salaryMinLimit: 0,
    salaryMaxLimit: 0,
    group: 'Trainee',
  },
];
