export const skillGroupSeed = [
  {
    value: 'Core algorithms',
    careerLevels: [
      'Trainee',
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: [
      'Front-end developer',
      'Back-end developer',
      'Full stack developer',
    ],
  },
  {
    value: 'Data structures',
    careerLevels: [
      'Trainee',
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: [
      'Front-end developer',
      'Back-end developer',
      'Full stack developer',
      'Swift developer',
    ],
  },
  {
    value: 'Patterns',
    careerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: [
      'Front-end developer',
      'Back-end developer',
      'Full stack developer',
    ],
  },
  {
    value: 'GIT',
    careerLevels: [
      'Trainee',
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: [
      'Front-end developer',
      'Back-end developer',
      'Full stack developer',
      'Swift developer',
    ],
  },
  {
    value: 'HTML',
    careerLevels: [
      'Trainee',
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Front-end developer', 'Full stack developer'],
  },
  {
    value: 'CSS',
    careerLevels: [
      'Trainee',
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Front-end developer', 'Full stack developer'],
  },
  {
    value: 'CSS frameworks (TailWind, bootstrap)',
    careerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Front-end developer', 'Full stack developer'],
  },
  {
    value: 'Functions (vanilla JS)',
    careerLevels: [
      'Trainee',
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: [
      'Front-end developer',
      'Back-end developer',
      'Full stack developer',
    ],
  },
  {
    value: 'Event loop (vanilla JS)',
    careerLevels: [
      'Trainee',
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: [
      'Front-end developer',
      'Back-end developer',
      'Full stack developer',
    ],
  },
  {
    value: 'Types (primitives + object) (vanilla JS)',
    careerLevels: [
      'Trainee',
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: [
      'Front-end developer',
      'Back-end developer',
      'Full stack developer',
    ],
  },
  {
    value: 'Data Structures JS (vanilla JS)',
    careerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: [
      'Front-end developer',
      'Back-end developer',
      'Full stack developer',
    ],
  },
  {
    value: 'WebWorkers / ServiceWorkers',
    careerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: ['Front-end developer', 'Full stack developer'],
  },
  {
    value: 'Typescript',
    careerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: [
      'Front-end developer',
      'Back-end developer',
      'Full stack developer',
    ],
  },
  {
    value: 'React',
    careerLevels: [
      'Trainee',
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Front-end developer', 'Full stack developer'],
  },
  {
    value: 'RXjs',
    careerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: ['Front-end developer', 'Full stack developer'],
  },
  {
    value: 'Websocket',
    careerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Front-end developer', 'Full stack developer'],
  },
  {
    value: 'GraphQL (JS)',
    careerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: [
      'Front-end developer',
      'Back-end developer',
      'Full stack developer',
    ],
  },
  {
    value: 'Browser storages (LocalStorage and etc)',
    careerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Front-end developer', 'Full stack developer'],
  },
  {
    value: 'Cross tabs communication',
    careerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Front-end developer', 'Full stack developer'],
  },
  {
    value: 'UI libraries (MaterialUI, react-botstrap)',
    careerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Front-end developer', 'Full stack developer'],
  },
  {
    value: 'Dev tools',
    careerLevels: [
      'Trainee',
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Front-end developer', 'Full stack developer'],
  },
  {
    value: 'Logging',
    careerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: ['Front-end developer', 'Full stack developer'],
  },
  {
    value: 'Cross-browser problems',
    careerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Front-end developer', 'Full stack developer'],
  },
  {
    value: 'Tests',
    careerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Front-end developer', 'Full stack developer'],
  },
  {
    value: 'Canvas',
    careerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Front-end developer', 'Full stack developer'],
  },
  {
    value: 'Multithread/multiprocess',
    careerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: [
      'Back-end developer',
      'Full stack developer',
      'Swift developer',
    ],
  },
  {
    value: 'File api',
    careerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Back-end developer', 'Full stack developer'],
  },
  {
    value: 'Stream',
    careerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Back-end developer', 'Full stack developer'],
  },
  {
    value: 'Cron',
    careerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Back-end developer', 'Full stack developer'],
  },
  {
    value: 'Express',
    careerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Back-end developer', 'Full stack developer'],
  },
  {
    value: 'ORM',
    careerLevels: [
      'Trainee',
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Back-end developer', 'Full stack developer'],
  },
  {
    value: 'DB (JS)',
    careerLevels: [
      'Trainee',
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Back-end developer', 'Full stack developer'],
  },
  {
    value: 'Google Firebase',
    careerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: [
      'Back-end developer',
      'Full stack developer',
      'Swift developer',
    ],
  },
  {
    value: 'AWS',
    careerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: [
      'Back-end developer',
      'Full stack developer',
      'Swift developer',
    ],
  },
  {
    value: 'Jenkins',
    careerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: [
      'Back-end developer',
      'Full stack developer',
      'Swift developer',
    ],
  },
  {
    value: 'CircleCI',
    careerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: ['Back-end developer', 'Full stack developer'],
  },
  {
    value: 'Docker',
    careerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: ['Back-end developer', 'Full stack developer'],
  },
  {
    value: 'Memory managment',
    careerLevels: [
      'Trainee',
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Swift developer'],
  },
  {
    value: 'Design Principles',
    careerLevels: [
      'Trainee',
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Swift developer'],
  },
  {
    value: 'Design Patterns',
    careerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Swift developer'],
  },
  {
    value: 'OOP',
    careerLevels: [
      'Trainee',
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Swift developer'],
  },
  {
    value: 'FRP',
    careerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    value: 'Objective-C',
    careerLevels: ['Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    value: 'Swift',
    careerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    value: 'SwitfUI',
    careerLevels: [
      'Trainee',
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Swift developer'],
  },
  {
    value: 'UIKit',
    careerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Swift developer'],
  },
  {
    value: 'Foundation',
    careerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Swift developer'],
  },
  {
    value: 'GCD',
    careerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    value: 'StoreKit',
    careerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    value: 'Push Notifications',
    careerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    value: 'Quartz',
    careerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    value: 'AVFoundation',
    careerLevels: ['Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    value: 'DB (Swift)',
    careerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    value: 'REST',
    careerLevels: [
      'Trainee',
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Swift developer'],
  },
  {
    value: 'GraphQL (Swift)',
    careerLevels: ['Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    value: 'Crashlytics',
    careerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    value: 'Profiling & Debuging',
    careerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    value: 'Unit Testing',
    careerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    value: 'RxSwift',
    careerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    value: 'Combine',
    careerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    value: 'Alamofire',
    careerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    value: 'Kingfisher',
    careerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    value: 'Cocoapods',
    careerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Swift developer'],
  },
  {
    value: 'SPM',
    careerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Swift developer'],
  },
  {
    value: 'Carthage',
    careerLevels: ['Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    value: 'Jenkins (Swift)',
    careerLevels: ['Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    value: 'Fastlane',
    careerLevels: ['Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    value: 'CircleCI (Swift)',
    careerLevels: ['Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
];
