export const skillGroupSeed = [
  {
    name: 'Core algorithms',
    carrerLevels: [
      'Trainee',
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: [
      'Front-end developer',
      'Back-end developer',
      'Full stack developer',
    ],
  },
  {
    name: 'Data structures',
    carrerLevels: [
      'Trainee',
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: [
      'Front-end developer',
      'Back-end developer',
      'Full stack developer',
      'Swift developer',
    ],
  },
  {
    name: 'Patterns',
    carrerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: [
      'Front-end developer',
      'Back-end developer',
      'Full stack developer',
    ],
  },
  {
    name: 'GIT',
    carrerLevels: [
      'Trainee',
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: [
      'Front-end developer',
      'Back-end developer',
      'Full stack developer',
      'Swift developer',
    ],
  },
  {
    name: 'HTML',
    carrerLevels: [
      'Trainee',
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Front-end developer', 'Full stack developer'],
  },
  {
    name: 'CSS',
    carrerLevels: [
      'Trainee',
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Front-end developer', 'Full stack developer'],
  },
  {
    name: 'CSS frameworks (TailWind, bootstrap)',
    carrerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Front-end developer', 'Full stack developer'],
  },
  {
    name: 'Functions (vanilla JS)',
    carrerLevels: [
      'Trainee',
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: [
      'Front-end developer',
      'Back-end developer',
      'Full stack developer',
    ],
  },
  {
    name: 'Event loop (vanilla JS)',
    carrerLevels: [
      'Trainee',
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: [
      'Front-end developer',
      'Back-end developer',
      'Full stack developer',
    ],
  },
  {
    name: 'Types (primitives + object) (vanilla JS)',
    carrerLevels: [
      'Trainee',
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: [
      'Front-end developer',
      'Back-end developer',
      'Full stack developer',
    ],
  },
  {
    name: 'Data Structures JS (vanilla JS)',
    carrerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: [
      'Front-end developer',
      'Back-end developer',
      'Full stack developer',
    ],
  },
  {
    name: 'WebWorkers / ServiceWorkers',
    carrerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: ['Front-end developer', 'Full stack developer'],
  },
  {
    name: 'Typescript',
    carrerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: [
      'Front-end developer',
      'Back-end developer',
      'Full stack developer',
    ],
  },
  {
    name: 'React',
    carrerLevels: [
      'Trainee',
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Front-end developer', 'Full stack developer'],
  },
  {
    name: 'RXjs',
    carrerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: ['Front-end developer', 'Full stack developer'],
  },
  {
    name: 'Websocket',
    carrerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Front-end developer', 'Full stack developer'],
  },
  {
    name: 'GraphQL (JS)',
    carrerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: [
      'Front-end developer',
      'Back-end developer',
      'Full stack developer',
    ],
  },
  {
    name: 'Browser storages (LocalStorage and etc)',
    carrerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Front-end developer', 'Full stack developer'],
  },
  {
    name: 'Cross tabs communication',
    carrerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Front-end developer', 'Full stack developer'],
  },
  {
    name: 'UI libraries (MaterialUI, react-botstrap)',
    carrerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Front-end developer', 'Full stack developer'],
  },
  {
    name: 'Dev tools',
    carrerLevels: [
      'Trainee',
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Front-end developer', 'Full stack developer'],
  },
  {
    name: 'Logging',
    carrerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: ['Front-end developer', 'Full stack developer'],
  },
  {
    name: 'Cross-browser problems',
    carrerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Front-end developer', 'Full stack developer'],
  },
  {
    name: 'Tests',
    carrerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Front-end developer', 'Full stack developer'],
  },
  {
    name: 'Canvas',
    carrerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Front-end developer', 'Full stack developer'],
  },
  {
    name: 'Multithread/multiprocess',
    carrerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: [
      'Back-end developer',
      'Full stack developer',
      'Swift developer',
    ],
  },
  {
    name: 'File api',
    carrerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Back-end developer', 'Full stack developer'],
  },
  {
    name: 'Stream',
    carrerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Back-end developer', 'Full stack developer'],
  },
  {
    name: 'Cron',
    carrerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Back-end developer', 'Full stack developer'],
  },
  {
    name: 'Express',
    carrerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Back-end developer', 'Full stack developer'],
  },
  {
    name: 'ORM',
    carrerLevels: [
      'Trainee',
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Back-end developer', 'Full stack developer'],
  },
  {
    name: 'DB (JS)',
    carrerLevels: [
      'Trainee',
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Back-end developer', 'Full stack developer'],
  },
  {
    name: 'Google Firebase',
    carrerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: [
      'Back-end developer',
      'Full stack developer',
      'Swift developer',
    ],
  },
  {
    name: 'AWS',
    carrerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: [
      'Back-end developer',
      'Full stack developer',
      'Swift developer',
    ],
  },
  {
    name: 'Jenkins',
    carrerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: [
      'Back-end developer',
      'Full stack developer',
      'Swift developer',
    ],
  },
  {
    name: 'CircleCI',
    carrerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: ['Back-end developer', 'Full stack developer'],
  },
  {
    name: 'Docker',
    carrerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: ['Back-end developer', 'Full stack developer'],
  },
  {
    name: 'Memory managment',
    carrerLevels: [
      'Trainee',
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Swift developer'],
  },
  {
    name: 'Design Principles',
    carrerLevels: [
      'Trainee',
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Swift developer'],
  },
  {
    name: 'Design Patterns',
    carrerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Swift developer'],
  },
  {
    name: 'OOP',
    carrerLevels: [
      'Trainee',
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Swift developer'],
  },
  {
    name: 'FRP',
    carrerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    name: 'Objective-C',
    carrerLevels: ['Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    name: 'Swift',
    carrerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    name: 'SwitfUI',
    carrerLevels: [
      'Trainee',
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Swift developer'],
  },
  {
    name: 'UIKit',
    carrerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Swift developer'],
  },
  {
    name: 'Foundation',
    carrerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Swift developer'],
  },
  {
    name: 'GCD',
    carrerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    name: 'StoreKit',
    carrerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    name: 'Push Notifications',
    carrerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    name: 'Quartz',
    carrerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    name: 'AVFoundation',
    carrerLevels: ['Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    name: 'DB (Swift)',
    carrerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    name: 'REST',
    carrerLevels: [
      'Trainee',
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Swift developer'],
  },
  {
    name: 'GraphQL (Swift)',
    carrerLevels: ['Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    name: 'Crashlytics',
    carrerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    name: 'Profiling & Debuging',
    carrerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    name: 'Unit Testing',
    carrerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    name: 'RxSwift',
    carrerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    name: 'Combine',
    carrerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    name: 'Alamofire',
    carrerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    name: 'Kingfisher',
    carrerLevels: ['Regular (Junior+)', 'Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    name: 'Cocoapods',
    carrerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Swift developer'],
  },
  {
    name: 'SPM',
    carrerLevels: [
      'Junior',
      'Regular (Junior+)',
      'Middle',
      'Middle+',
      'Senior',
    ],
    positions: ['Swift developer'],
  },
  {
    name: 'Carthage',
    carrerLevels: ['Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    name: 'Jenkins (Swift)',
    carrerLevels: ['Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    name: 'Fastlane',
    carrerLevels: ['Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
  {
    name: 'CircleCI (Swift)',
    carrerLevels: ['Middle', 'Middle+', 'Senior'],
    positions: ['Swift developer'],
  },
];
