export const userSeed = [
  {
    firstName: 'Dmitriy',
    lastName: 'Homza',
    email: 'dm.homza@gmail.com',
    password: 'qwertasdfg',
    role: 'sudo',
    isActive: true,
    birthday: '2011-01-23T22:15:51.000Z',
    position: 'Full stack trainee',
  },
  {
    firstName: 'Veronika',
    lastName: 'Moseichik',
    email: 'moseikus@gmail.com',
    password: 'qwertasdfg',
    role: 'admin',
    isActive: true,
    birthday: '2011-01-23T22:15:51.000Z',
    position: 'Back-end trainee',
  },
  {
    firstName: 'Eugenuiy',
    lastName: 'Lazarev',
    email: 'laraz@gmail.com',
    password: 'qwertasdfg',
    role: 'user',
    isActive: true,
    birthday: '2011-01-23T22:15:51.000Z',
    position: 'Swift developer',
  },
];
