export const vacationsSeed = [
  {
    id: '104ff990-9b17-4070-a7d6-1c67fded12c2',
    policy: 'VAC',
    start: new Date(),
    end: new Date(),
    status: 'submitted',
    reason: 'It is time to relax',
    user: 'Dmitriy Homza',
  },
  {
    id: '142edd25-69d1-4c96-aa5b-79b6f4437b2c',
    policy: 'SICK',
    start: new Date(),
    end: new Date(),
    status: 'submitted',
    reason: 'It is time to relax',
    user: 'Veronika Moseichik',
  },
  {
    id: '1561b651-34cc-43f5-a3fd-7634537082e3',
    policy: 'VAC',
    start: new Date(),
    end: new Date(),
    status: 'submitted',
    reason: 'It is time to relax',
    user: 'Eugenuiy Lazarev',
  },
  {
    id: '2f340400-01d9-4cab-b303-72e4c449d5b6',
    policy: 'VAC',
    start: new Date(),
    end: new Date(),
    status: 'denied',
    reason: 'It is time to relax',
    user: 'Jake Gyllenhaal',
  },
];
