export const userSeed = [
  {
    firstName: 'Dmitriy',
    lastName: 'Homza',
    email: 'dm.homza@gmail.com',
    password: 'qwertasdfg',
    role: 1,
  },
  {
    firstName: 'Veronika',
    lastName: 'Moseichik',
    email: 'moseikus@gmail.com',
    password: 'qwertasdfg',
    role: 2,
  },
  {
    firstName: 'Eugenuiy',
    lastName: 'Lazarev',
    email: 'laraz@gmail.com',
    password: 'qwertasdfg',
    role: 3,
  },
  {
    firstName: 'A',
    lastName: 'A',
    email: 'a@gmail.com',
    password: 'qwertasdfg',
    role: 1,
  },
  {
    firstName: 'B',
    lastName: 'B',
    email: 'a@gmail.com',
    password: 'qwertasdfg',
    role: 1,
  },
  {
    firstName: 'C',
    lastName: 'C',
    email: 'a@gmail.com',
    password: 'qwertasdfg',
    role: 1,
  },
  {
    firstName: 'A',
    lastName: 'A',
    email: 'a@gmail.com',
    password: 'qwertasdfg',
    role: 1,
  },
  {
    firstName: 'A',
    lastName: 'A',
    email: 'a@gmail.com',
    password: 'qwertasdfg',
    role: 1,
  },
  {
    firstName: 'H',
    lastName: 'H',
    email: 'a@gmail.com',
    password: 'qwertasdfg',
    role: 1,
  },
  {
    firstName: 'G',
    lastName: 'G',
    email: 'a@gmail.com',
    password: 'qwertasdfg',
    role: 1,
  },
  {
    firstName: 'D',
    lastName: 'D',
    email: 'a@gmail.com',
    password: 'qwertasdfg',
    role: 1,
  },
  {
    firstName: 'A',
    lastName: 'A',
    email: 'a@gmail.com',
    password: 'qwertasdfg',
    role: 1,
  },
  {
    firstName: 'A',
    lastName: 'A',
    email: 'a@gmail.com',
    password: 'qwertasdfg',
    role: 1,
  },
  {
    firstName: 'A',
    lastName: 'A',
    email: 'a@gmail.com',
    password: 'qwertasdfg',
    role: 1,
  },
  {
    firstName: 'A',
    lastName: 'A',
    email: 'a@gmail.com',
    password: 'qwertasdfg',
    role: 1,
  },
];
